[jit] Make the stelem helper calls non-virtual if possible.
mono/mono pull request #20681
Opened 2020-12-20 09:15 UTC by vargaz

2020-12-20 09:16 UTC, vargaz commented
This helps especially on wasm since virtual calls generate a lot of code there. This decreases the size of an aot-ed hello world on wasm by about 17k.

2020-12-21 15:48 UTC, lambdageek approved these changes

2020-12-21 16:01 UTC, lambdageek commented
It's failing a regression test in dotnet/runtime https://github.com/dotnet/runtime/blob/master/src/tests/JIT/Regression/VS-ia64-JIT/V1.2-M01/b12390/test_04a.il

2020-12-21 16:06 UTC, lambdageek requested changes

2020-12-21 16:06 UTC, lambdageek commented on mono/mini/method-to-ir.c
> +				return mono_emit_method_call (cfg, helper, iargs, NULL);
the problem is that `mono_marshal_get_vritual_stelemref` call above is passed `obj_array` as the type, which makes it always choose the `STELEMREF_OBJECT` wrapper kind which has no typecheck at all.  So you need to pass a more precise static class.

(Seems like it should've already been broken for the virtual case.  I'm not sure.)

2020-12-21 16:08 UTC, lambdageek approved these changes

2020-12-22 19:52 UTC, vargaz commented
@monojenkins build failed

2021-01-02 05:49 UTC, vargaz commented
@monojenkins build failed

2021-01-02 13:56 UTC, vargaz commented
@monojenkins build failed

2021-01-02 16:29 UTC, merged